[package]
name = "raytrace"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.12"
crossfont = "0.5"
gl = "0.14"
image = "0.24"
ultraviolet = { version = "0.6" }
glutin = "0.30"
winit = "0.27"
raw-window-handle = "0.5.0"
