[package]
name = "raytrace"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.12"
crossfont = "0.5"
gl = "0.14"
glfw = { version = "0.47", default-features = false }
image = "0.24"
ultraviolet = { version = "0.6" }
